[2024-09-11T14:59:41.362759+00:00] app.ERROR: Error al crear usuario: An exception occurred while executing a query: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "usuarios_nombre_usuario_key" DETAIL:  Key (nombre_usuario)=(haki123) already exists. {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 7): An exception occurred while executing a query: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \"usuarios_nombre_usuario_key\"\nDETAIL:  Key (nombre_usuario)=(haki123) already exists. at /var/www/comedor-servicio/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:53)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \"usuarios_nombre_usuario_key\"\nDETAIL:  Key (nombre_usuario)=(haki123) already exists. at /var/www/comedor-servicio/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 23505): SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \"usuarios_nombre_usuario_key\"\nDETAIL:  Key (nombre_usuario)=(haki123) already exists. at /var/www/comedor-servicio/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:55)"} []
[2024-09-11T09:01:51.749275-06:00] app.ERROR: Error al crear usuario: An exception occurred while executing a query: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "usuarios_nombre_usuario_key" DETAIL:  Key (nombre_usuario)=(haki123) already exists. {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 7): An exception occurred while executing a query: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \"usuarios_nombre_usuario_key\"\nDETAIL:  Key (nombre_usuario)=(haki123) already exists. at /var/www/comedor-servicio/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:53)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \"usuarios_nombre_usuario_key\"\nDETAIL:  Key (nombre_usuario)=(haki123) already exists. at /var/www/comedor-servicio/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 23505): SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \"usuarios_nombre_usuario_key\"\nDETAIL:  Key (nombre_usuario)=(haki123) already exists. at /var/www/comedor-servicio/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:55)"} []
[2024-09-11T09:05:27.580623-06:00] app.ERROR: Error inesperado al crear usuario: El nombre de usuario ya está en uso. {"exception":"[object] (RuntimeException(code: 0): El nombre de usuario ya está en uso. at /var/www/comedor-servicio/src/Repository/UsuarioRepository.php:78)"} []
[2024-09-11T09:07:03.795884-06:00] app.ERROR: Error inesperado al crear usuario: El nombre de usuario ya está en uso. {"exception":"[object] (RuntimeException(code: 0): El nombre de usuario ya está en uso. at /var/www/comedor-servicio/src/Repository/UsuarioRepository.php:78)"} []
[2024-09-11T09:07:58.779179-06:00] app.ERROR: Error inesperado al crear usuario: El nombre de usuario ya está en uso. {"exception":"[object] (RuntimeException(code: 0): El nombre de usuario ya está en uso. at /var/www/comedor-servicio/src/Repository/UsuarioRepository.php:78)"} []
[2024-09-11T09:08:31.089161-06:00] app.ERROR: Error inesperado al crear usuario: El nombre de usuario ya está en uso. {"exception":"[object] (RuntimeException(code: 0): El nombre de usuario ya está en uso. at /var/www/comedor-servicio/src/Repository/UsuarioRepository.php:78)"} []
[2024-09-11T09:09:42.942672-06:00] app.ERROR: Error inesperado al crear usuario: El nombre de usuario ya está en uso. {"exception":"[object] (RuntimeException(code: 0): El nombre de usuario ya está en uso. at /var/www/comedor-servicio/src/Repository/UsuarioRepository.php:78)"} []
[2024-09-11T09:09:51.350784-06:00] app.ERROR: Error inesperado al crear usuario: El correo ya está en uso. {"exception":"[object] (RuntimeException(code: 0): El correo ya está en uso. at /var/www/comedor-servicio/src/Repository/UsuarioRepository.php:86)"} []
[2024-09-11T09:12:38.316129-06:00] app.ERROR: Error inesperado al crear usuario: El nombre de usuario ya está en uso. {"exception":"[object] (RuntimeException(code: 0): El nombre de usuario ya está en uso. at /var/www/comedor-servicio/src/Repository/UsuarioRepository.php:78)"} []
[2024-09-11T09:12:46.948989-06:00] app.ERROR: Error inesperado al crear usuario: El correo ya está en uso. {"exception":"[object] (RuntimeException(code: 0): El correo ya está en uso. at /var/www/comedor-servicio/src/Repository/UsuarioRepository.php:86)"} []
[2024-09-11T10:21:48.319414-06:00] app.ERROR: Error inesperado al crear usuario: El nombre de usuario ya está en uso. {"exception":"[object] (RuntimeException(code: 0): El nombre de usuario ya está en uso. at /var/www/comedor-servicio/src/Repository/UsuarioRepository.php:78)"} []
[2024-09-11T10:21:57.770163-06:00] app.ERROR: Error inesperado al crear usuario: El correo ya está en uso. {"exception":"[object] (RuntimeException(code: 0): El correo ya está en uso. at /var/www/comedor-servicio/src/Repository/UsuarioRepository.php:86)"} []
[2024-09-11T10:37:01.303547-06:00] app.ERROR: Error al obtener usuarios: An exception occurred while executing a query: SQLSTATE[42703]: Undefined column: 7 ERROR:  column t0.isadmin does not exist LINE 1: ...7, t0.fecha_modificacion AS fecha_modificacion_8, t0.isAdmin...                                                              ^ HINT:  Perhaps you meant to reference the column "t0.isAdmin". {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 7): An exception occurred while executing a query: SQLSTATE[42703]: Undefined column: 7 ERROR:  column t0.isadmin does not exist\nLINE 1: ...7, t0.fecha_modificacion AS fecha_modificacion_8, t0.isAdmin...\n                                                             ^\nHINT:  Perhaps you meant to reference the column \"t0.isAdmin\". at /var/www/comedor-servicio/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:68)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[42703]: Undefined column: 7 ERROR:  column t0.isadmin does not exist\nLINE 1: ...7, t0.fecha_modificacion AS fecha_modificacion_8, t0.isAdmin...\n                                                             ^\nHINT:  Perhaps you meant to reference the column \"t0.isAdmin\". at /var/www/comedor-servicio/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 42703): SQLSTATE[42703]: Undefined column: 7 ERROR:  column t0.isadmin does not exist\nLINE 1: ...7, t0.fecha_modificacion AS fecha_modificacion_8, t0.isAdmin...\n                                                             ^\nHINT:  Perhaps you meant to reference the column \"t0.isAdmin\". at /var/www/comedor-servicio/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:57)"} []
[2024-09-11T10:41:28.101042-06:00] app.ERROR: Error al obtener usuarios: An exception occurred while executing a query: SQLSTATE[42703]: Undefined column: 7 ERROR:  column t0.isadmin does not exist LINE 1: ...7, t0.fecha_modificacion AS fecha_modificacion_8, t0.isAdmin...                                                              ^ HINT:  Perhaps you meant to reference the column "t0.isAdmin". {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 7): An exception occurred while executing a query: SQLSTATE[42703]: Undefined column: 7 ERROR:  column t0.isadmin does not exist\nLINE 1: ...7, t0.fecha_modificacion AS fecha_modificacion_8, t0.isAdmin...\n                                                             ^\nHINT:  Perhaps you meant to reference the column \"t0.isAdmin\". at /var/www/comedor-servicio/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:68)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[42703]: Undefined column: 7 ERROR:  column t0.isadmin does not exist\nLINE 1: ...7, t0.fecha_modificacion AS fecha_modificacion_8, t0.isAdmin...\n                                                             ^\nHINT:  Perhaps you meant to reference the column \"t0.isAdmin\". at /var/www/comedor-servicio/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 42703): SQLSTATE[42703]: Undefined column: 7 ERROR:  column t0.isadmin does not exist\nLINE 1: ...7, t0.fecha_modificacion AS fecha_modificacion_8, t0.isAdmin...\n                                                             ^\nHINT:  Perhaps you meant to reference the column \"t0.isAdmin\". at /var/www/comedor-servicio/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:57)"} []
[2024-09-11T10:53:24.873434-06:00] app.ERROR: Error al obtener usuarios: An exception occurred while executing a query: SQLSTATE[42703]: Undefined column: 7 ERROR:  column t0.isadmin does not exist LINE 1: ...7, t0.fecha_modificacion AS fecha_modificacion_8, t0.isAdmin...                                                              ^ HINT:  Perhaps you meant to reference the column "t0.isAdmin". {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 7): An exception occurred while executing a query: SQLSTATE[42703]: Undefined column: 7 ERROR:  column t0.isadmin does not exist\nLINE 1: ...7, t0.fecha_modificacion AS fecha_modificacion_8, t0.isAdmin...\n                                                             ^\nHINT:  Perhaps you meant to reference the column \"t0.isAdmin\". at /var/www/comedor-servicio/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:68)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[42703]: Undefined column: 7 ERROR:  column t0.isadmin does not exist\nLINE 1: ...7, t0.fecha_modificacion AS fecha_modificacion_8, t0.isAdmin...\n                                                             ^\nHINT:  Perhaps you meant to reference the column \"t0.isAdmin\". at /var/www/comedor-servicio/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 42703): SQLSTATE[42703]: Undefined column: 7 ERROR:  column t0.isadmin does not exist\nLINE 1: ...7, t0.fecha_modificacion AS fecha_modificacion_8, t0.isAdmin...\n                                                             ^\nHINT:  Perhaps you meant to reference the column \"t0.isAdmin\". at /var/www/comedor-servicio/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:57)"} []
[2024-09-11T10:53:27.885057-06:00] app.ERROR: Error al obtener usuarios: An exception occurred while executing a query: SQLSTATE[42703]: Undefined column: 7 ERROR:  column t0.isadmin does not exist LINE 1: ...7, t0.fecha_modificacion AS fecha_modificacion_8, t0.isadmin...                                                              ^ HINT:  Perhaps you meant to reference the column "t0.isAdmin". {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 7): An exception occurred while executing a query: SQLSTATE[42703]: Undefined column: 7 ERROR:  column t0.isadmin does not exist\nLINE 1: ...7, t0.fecha_modificacion AS fecha_modificacion_8, t0.isadmin...\n                                                             ^\nHINT:  Perhaps you meant to reference the column \"t0.isAdmin\". at /var/www/comedor-servicio/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:68)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[42703]: Undefined column: 7 ERROR:  column t0.isadmin does not exist\nLINE 1: ...7, t0.fecha_modificacion AS fecha_modificacion_8, t0.isadmin...\n                                                             ^\nHINT:  Perhaps you meant to reference the column \"t0.isAdmin\". at /var/www/comedor-servicio/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 42703): SQLSTATE[42703]: Undefined column: 7 ERROR:  column t0.isadmin does not exist\nLINE 1: ...7, t0.fecha_modificacion AS fecha_modificacion_8, t0.isadmin...\n                                                             ^\nHINT:  Perhaps you meant to reference the column \"t0.isAdmin\". at /var/www/comedor-servicio/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:57)"} []
[2024-09-11T10:53:46.750841-06:00] app.ERROR: Error al obtener usuarios: An exception occurred while executing a query: SQLSTATE[42703]: Undefined column: 7 ERROR:  column t0.isadmin does not exist LINE 1: ...7, t0.fecha_modificacion AS fecha_modificacion_8, t0.isadmin...                                                              ^ HINT:  Perhaps you meant to reference the column "t0.isAdmin". {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 7): An exception occurred while executing a query: SQLSTATE[42703]: Undefined column: 7 ERROR:  column t0.isadmin does not exist\nLINE 1: ...7, t0.fecha_modificacion AS fecha_modificacion_8, t0.isadmin...\n                                                             ^\nHINT:  Perhaps you meant to reference the column \"t0.isAdmin\". at /var/www/comedor-servicio/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:68)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[42703]: Undefined column: 7 ERROR:  column t0.isadmin does not exist\nLINE 1: ...7, t0.fecha_modificacion AS fecha_modificacion_8, t0.isadmin...\n                                                             ^\nHINT:  Perhaps you meant to reference the column \"t0.isAdmin\". at /var/www/comedor-servicio/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 42703): SQLSTATE[42703]: Undefined column: 7 ERROR:  column t0.isadmin does not exist\nLINE 1: ...7, t0.fecha_modificacion AS fecha_modificacion_8, t0.isadmin...\n                                                             ^\nHINT:  Perhaps you meant to reference the column \"t0.isAdmin\". at /var/www/comedor-servicio/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:57)"} []
[2024-09-12T13:56:58.718299-06:00] app.ERROR: Error en el proceso de login: El nombre de usuario es incorrecto. {"exception":"[object] (RuntimeException(code: 0): El nombre de usuario es incorrecto. at /var/www/comedor-servicio/src/Repository/AuthRepository.php:35)"} []
[2024-09-12T13:57:13.789321-06:00] app.ERROR: Error en el proceso de login: El nombre de usuario es incorrecto. {"exception":"[object] (RuntimeException(code: 0): El nombre de usuario es incorrecto. at /var/www/comedor-servicio/src/Repository/AuthRepository.php:35)"} []
[2024-09-12T13:57:53.291527-06:00] app.ERROR: Error en el proceso de login: El nombre de usuario es incorrecto. {"exception":"[object] (RuntimeException(code: 0): El nombre de usuario es incorrecto. at /var/www/comedor-servicio/src/Repository/AuthRepository.php:35)"} []
[2024-09-12T13:59:52.388270-06:00] app.ERROR: Error en el proceso de login: El nombre de usuario es incorrecto. {"exception":"[object] (RuntimeException(code: 0): El nombre de usuario es incorrecto. at /var/www/comedor-servicio/src/Repository/AuthRepository.php:35)"} []
[2024-09-12T14:00:25.492653-06:00] app.ERROR: Error inesperado en el proceso de login: App\Repository\AuthRepository::verifyPassword(): Argument #2 ($hash) must be of type string, null given, called in /var/www/comedor-servicio/src/Repository/AuthRepository.php on line 38 {"exception":"[object] (TypeError(code: 0): App\\Repository\\AuthRepository::verifyPassword(): Argument #2 ($hash) must be of type string, null given, called in /var/www/comedor-servicio/src/Repository/AuthRepository.php on line 38 at /var/www/comedor-servicio/src/Repository/AuthRepository.php:78)"} []
[2024-09-12T14:00:54.233905-06:00] app.ERROR: Error inesperado en el proceso de login: App\Repository\AuthRepository::verifyPassword(): Argument #2 ($hash) must be of type string, null given, called in /var/www/comedor-servicio/src/Repository/AuthRepository.php on line 38 {"exception":"[object] (TypeError(code: 0): App\\Repository\\AuthRepository::verifyPassword(): Argument #2 ($hash) must be of type string, null given, called in /var/www/comedor-servicio/src/Repository/AuthRepository.php on line 38 at /var/www/comedor-servicio/src/Repository/AuthRepository.php:78)"} []
[2024-09-12T14:02:13.903318-06:00] app.ERROR: Error inesperado en el proceso de login: App\Repository\AuthRepository::verifyPassword(): Argument #2 ($hash) must be of type string, null given, called in /var/www/comedor-servicio/src/Repository/AuthRepository.php on line 38 {"exception":"[object] (TypeError(code: 0): App\\Repository\\AuthRepository::verifyPassword(): Argument #2 ($hash) must be of type string, null given, called in /var/www/comedor-servicio/src/Repository/AuthRepository.php on line 38 at /var/www/comedor-servicio/src/Repository/AuthRepository.php:78)"} []
[2024-09-12T14:02:42.829413-06:00] app.ERROR: Error inesperado en el proceso de login: Cannot access private property App\Entity\Usuario::$contrasenia {"exception":"[object] (Error(code: 0): Cannot access private property App\\Entity\\Usuario::$contrasenia at /var/www/comedor-servicio/src/Repository/AuthRepository.php:38)"} []
[2024-09-12T14:04:51.922524-06:00] app.ERROR: Error en el proceso de login: El nombre de usuario es incorrecto. {"exception":"[object] (RuntimeException(code: 0): El nombre de usuario es incorrecto. at /var/www/comedor-servicio/src/Repository/AuthRepository.php:35)"} []
[2024-09-12T14:07:07.743703-06:00] app.ERROR: Error inesperado en el proceso de login: Cannot access private property App\Entity\Usuario::$contrasenia {"exception":"[object] (Error(code: 0): Cannot access private property App\\Entity\\Usuario::$contrasenia at /var/www/comedor-servicio/src/Repository/AuthRepository.php:38)"} []
[2024-09-12T14:08:06.064307-06:00] app.ERROR: Error inesperado en el proceso de login: Cannot access private property App\Entity\Usuario::$contrasenia {"exception":"[object] (Error(code: 0): Cannot access private property App\\Entity\\Usuario::$contrasenia at /var/www/comedor-servicio/src/Repository/AuthRepository.php:38)"} []
[2024-09-12T14:08:28.930192-06:00] app.ERROR: Error en el proceso de login: Error al generar el token JWT: key must be a string when using hmac {"exception":"[object] (RuntimeException(code: 0): Error al generar el token JWT: key must be a string when using hmac at /var/www/comedor-servicio/src/Repository/AuthRepository.php:60)"} []
